# Description : A config of parser
# Author      : Siyuexi

max_length: 15
max_depth: 3
max_child: 100
t_extract : 0.5
t_aggregate: 0.4
regex: # the regex order is important: The first must be timestame and the last must be splitter
  -
    name: timestamp
    re: '\[[0-9]{2}:[0-9]{2}:[0-9]{2}\]'
    symbol: <!>
  -
    name: ip
    re: '(/|)([0-9]+\.){3}[0-9]+(:[0-9]+|)(:|)'
    symbol: <*ip>
  - 
    name: dir
    re: '(([A-Z]:)|)(/\S+)+'
    symbol: <*dr>
  -
    name: int
    re: '(?<=[^A-Za-z0-9])(\-?\+?\d+)(?=[^A-Za-z0-9])|[0-9]+$'
    symbol: <*it>
  -
    name: bool
    re: '(=*|)(True)|(False)|(true)|(false)'
    symbol: <*bl>
  -
    name: splitter
    re: '[-\+\=\|]+'
    symbol: <?>